DROP TABLE IF EXISTS machine_info;

CREATE TABLE machine_info
(
  id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
  ip VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  name VARCHAR(100) NULL DEFAULT NULL COMMENT '应用名称',
  desc VARCHAR(500) NULL DEFAULT NULL COMMENT '机器描述',
  regexp VARCHAR(500) NULL DEFAULT NULL COMMENT '机器描述',
  enterTime VARCHAR(30) NULL DEFAULT NULL COMMENT '进入时间',
  lostTime VARCHAR(30) NULL DEFAULT NULL COMMENT '出去时间',
  status INT(11) NOT NULL DEFAULT 0 COMMENT '状态',
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS method_info;

CREATE TABLE method_info
(
  id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
  pid BIGINT(20) NOT NULL auto_increment COMMENT '父ID',
  ip VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  typeName VARCHAR(100) NULL DEFAULT NULL COMMENT '类全路径',
  methodName VARCHAR(100) NULL DEFAULT NULL COMMENT '方法名称',
  status INT(11) NOT NULL DEFAULT 0 COMMENT '状态',
  PRIMARY KEY (id)
);