DROP TABLE IF EXISTS machine;

CREATE TABLE machine
(
  id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
  ip VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  name VARCHAR(100) NULL DEFAULT NULL COMMENT '应用名称',
  desc VARCHAR(100) NULL DEFAULT NULL COMMENT '机器描述',
  enterTime VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  lostTime VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  status INT(11) NULL DEFAULT NULL COMMENT '状态',
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS method;

CREATE TABLE machine
(
  id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
  ip VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  typeName VARCHAR(100) NULL DEFAULT NULL COMMENT '类全路径',
  methodName VARCHAR(100) NULL DEFAULT NULL COMMENT '方法名称',
  status INT(11) NULL DEFAULT NULL COMMENT '状态',
  PRIMARY KEY (id)
);