/*DROP TABLE IF EXISTS machine_info;*/

CREATE TABLE IF NOT EXISTS machine_info
(
  id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
  ip VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  name VARCHAR(200) NULL DEFAULT NULL COMMENT '应用名称',
  desc VARCHAR(500) NULL DEFAULT NULL COMMENT '机器描述',
  regexp VARCHAR(500) NULL DEFAULT NULL COMMENT '匹配正则',
  enterTime VARCHAR(30) NULL DEFAULT NULL COMMENT '进入时间',
  lostTime VARCHAR(30) NULL DEFAULT NULL COMMENT '出去时间',
  status INT(11) NOT NULL DEFAULT 0 COMMENT '状态',
  PRIMARY KEY (id)
);

/*DROP TABLE IF EXISTS method_info;*/

CREATE TABLE  IF NOT EXISTS method_info
(
  id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
  pid BIGINT(20) NOT NULL auto_increment COMMENT '父ID',
  ip VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  type_name VARCHAR(800) NULL DEFAULT NULL COMMENT '类全路径',
  method_name VARCHAR(300) NULL DEFAULT NULL COMMENT '方法名称',
  status INT(11) NOT NULL DEFAULT 0 COMMENT '状态',
  PRIMARY KEY (id)
);

/*DROP TABLE IF EXISTS break_info;
*/
CREATE TABLE  IF NOT EXISTS break_info
(
  id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
  ip VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP',
  break_content VARCHAR(1000) NULL DEFAULT NULL COMMENT '类方法',
  PRIMARY KEY (id)
);