 ##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server:
  port: 8181                    # 指定实例的端口


